# Generated by Django 6.0.4 on 2026-04-09 05:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, help_text='Bangladeshi phone number (01XXXXXXXXX). Used as login identifier.', max_length=15, unique=True)),
                ('full_name', models.CharField(help_text='Display name shown on listings and profile.', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('profile_completed', models.BooleanField(default=False, help_text='True after Step 1 of profile completion is submitted.')),
                ('marketing_consent', models.BooleanField(default=False, help_text='User opted in to marketing communications.')),
                ('trust_level', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified'), ('partner', 'Bhara Partner')], default='unverified', help_text='unverified | verified | partner', max_length=20)),
                ('is_approved', models.BooleanField(default=None, help_text='None = no documents submitted or pending review. True = admin approved. False = admin rejected.', null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('date_of_birth', models.DateField(blank=True, help_text='Must be 18+ years old.', null=True)),
                ('district', models.CharField(blank=True, help_text='Selected from BD district list.', max_length=100)),
                ('thana', models.CharField(blank=True, help_text='Selected from thanas under chosen district.', max_length=100)),
                ('full_address', models.TextField(blank=True, help_text='Free-text full address after district/thana selection.')),
                ('email', models.EmailField(blank=True, help_text='Optional. Collected during profile completion. Not used for login.', max_length=254, null=True)),
                ('nid_number', models.CharField(blank=True, help_text='NID number typed by user. No format enforcement — admin visually verifies.', max_length=20, null=True)),
                ('nid_image', models.ImageField(blank=True, help_text='Photo of govt ID (NID front, passport, or driving license).', null=True, upload_to='identity/nid/')),
                ('institutional_id_image', models.ImageField(blank=True, help_text='Optional. University or office ID photo.', null=True, upload_to='identity/institutional/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
    ]
