# Generated by Django 6.0.4 on 2026-06-11 08:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('photography_videography', 'Photography & Videography'), ('sports_outdoor', 'Sports & Outdoor'), ('camping_hiking', 'Camping & Hiking'), ('travel_luggage', 'Travel & Luggage'), ('event_party', 'Event & Party'), ('fashion_accessories', 'Fashion & Accessories'), ('electronics', 'Electronics'), ('tools_equipment', 'Tools & Equipment'), ('musical_instruments', 'Musical Instruments'), ('other', 'Other')], db_index=True, max_length=50)),
                ('product_type', models.CharField(choices=[('camera', 'photography_videography'), ('lens', 'photography_videography'), ('gimbal', 'photography_videography'), ('tripod', 'photography_videography'), ('drone', 'photography_videography'), ('lighting', 'photography_videography'), ('video_camera', 'photography_videography'), ('microphone', 'photography_videography'), ('stabilizer', 'photography_videography'), ('slider', 'photography_videography'), ('reflector', 'photography_videography'), ('monitor', 'photography_videography'), ('memory_card', 'photography_videography'), ('battery', 'photography_videography'), ('charger', 'photography_videography'), ('light_stand', 'photography_videography'), ('softbox', 'photography_videography'), ('backdrop', 'photography_videography'), ('cricket_bat', 'sports_outdoor'), ('football', 'sports_outdoor'), ('badminton_racket', 'sports_outdoor'), ('helmet', 'sports_outdoor'), ('sports_gear', 'sports_outdoor'), ('running_shoes', 'sports_outdoor'), ('bicycle', 'sports_outdoor'), ('skipping_rope', 'sports_outdoor'), ('backpack', 'camping_hiking'), ('headlamp', 'camping_hiking'), ('gas_can', 'camping_hiking'), ('raincover', 'camping_hiking'), ('poncho', 'camping_hiking'), ('jacket', 'camping_hiking'), ('sleeping_bag', 'camping_hiking'), ('tent', 'camping_hiking'), ('stove', 'camping_hiking'), ('water_bottle', 'camping_hiking'), ('hiking_pole', 'camping_hiking'), ('camping_chair', 'camping_hiking'), ('suitcase', 'travel_luggage'), ('travel_adapter', 'travel_luggage'), ('power_bank', 'travel_luggage'), ('travel_bag', 'travel_luggage'), ('trolley', 'travel_luggage'), ('sound_system', 'event_party'), ('decorations', 'event_party'), ('chair', 'event_party'), ('table', 'event_party'), ('stage_light', 'event_party'), ('projector', 'event_party'), ('tent', 'event_party'), ('formal_wear', 'fashion_accessories'), ('jewelry', 'fashion_accessories'), ('costume', 'fashion_accessories'), ('watch', 'fashion_accessories'), ('sunglasses', 'fashion_accessories'), ('laptop', 'electronics'), ('tablet', 'electronics'), ('smartphone', 'electronics'), ('projector', 'electronics'), ('speaker', 'electronics'), ('tv', 'electronics'), ('printer', 'electronics'), ('scanner', 'electronics'), ('router', 'electronics'), ('power_tools', 'tools_equipment'), ('hand_tools', 'tools_equipment'), ('measuring_tape', 'tools_equipment'), ('drill_machine', 'tools_equipment'), ('ladder', 'tools_equipment'), ('cleaning_equipment', 'tools_equipment'), ('guitar', 'musical_instruments'), ('keyboard', 'musical_instruments'), ('harmonium', 'musical_instruments'), ('tabla', 'musical_instruments'), ('microphone', 'musical_instruments'), ('amplifier', 'musical_instruments'), ('drum', 'musical_instruments'), ('violin', 'musical_instruments'), ('other', 'other')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(db_index=True, max_length=255)),
                ('security_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_year', models.CharField(max_length=4)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ownership_history', models.CharField(choices=[('firsthand', 'First Hand'), ('secondhand', 'Second Hand')], max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active - Available for Rent'), ('suspended', 'Suspended - Listing Disabled')], db_index=True, default='active', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('rental_count', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(max_length=255, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.product')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration_unit', models.CharField(choices=[('day', 'Per Day'), ('week', 'Per Week'), ('month', 'Per Month')], max_length=10)),
                ('price', models.PositiveIntegerField(help_text='Price per duration unit in Taka')),
                ('max_period', models.PositiveIntegerField(default=30, help_text='Maximum rental period in the specified duration unit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_tiers', to='listings.product')),
            ],
            options={
                'verbose_name': 'Pricing Tier',
                'verbose_name_plural': 'Pricing Tiers',
                'ordering': ['duration_unit', 'price'],
                'constraints': [models.UniqueConstraint(fields=('product', 'duration_unit'), name='unique_duration_unit_per_product')],
            },
        ),
        migrations.CreateModel(
            name='UnavailablePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Single unavailable date')),
                ('is_range', models.BooleanField(default=False)),
                ('range_start', models.DateField(blank=True, null=True)),
                ('range_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unavailable_periods', to='listings.product')),
            ],
            options={
                'verbose_name': 'Unavailable Period',
                'verbose_name_plural': 'Unavailable Periods',
                'ordering': ['date'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_range', False), models.Q(('is_range', True), ('range_start__isnull', False), ('range_end__isnull', False), ('range_end__gte', models.F('range_start'))), _connector='OR')), name='valid_period_range')],
            },
        ),
    ]
