# Generated by Django 6.0.4 on 2026-06-11 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_product_product_status_created_idx'),
        ('rentals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['product', 'status', 'start_date', 'end_date'], name='rental_overlap_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['renter', 'status'], name='rental_renter_status_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['owner', 'status'], name='rental_owner_status_idx'),
        ),
    ]
