# Generated by Django 6.0.4 on 2026-06-11 13:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_product_product_status_created_idx'),
        ('rentals', '0002_rental_rental_overlap_idx_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'direction'], name='review_product_dir_idx'),
        ),
    ]
